language: scala
sudo: required
jdk: oraclejdk8
dist: trusty

services:
  - docker

scala:
  - 2.12.4

before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_575a6d494c46_key
  -iv $encrypted_575a6d494c46_iv -in travis/secrets.tar.enc -out travis/secrets.tar
  -d; tar xv -C travis -f travis/secrets.tar; fi

script:
  - ./test.sh

after_success:
# send every push to master to sonatype
  - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ] && [ "$TRAVIS_BRANCH" = "master" ]; then { sbt publishSigned ;} fi;
# send releases / tags to maven central
  - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ] && [ -n "$TRAVIS_TAG" ]; then { sbt publishSigned && sbt sonatypeRelease ; } fi;

before_deploy:
  # create release zip
  - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ] && [ -n "$TRAVIS_TAG" ]; then { sbt universal:packageBin ; } fi;

# Improvement: move logic out of docker_push.sh into .travis.yml
deploy:
  - provider: script
    script: bash docker_push.sh
    skip_cleanup: true
    on:
      tags: true
      condition: -z "$TRAVIS_PULL_REQUEST_BRANCH"
  - provider: script
    script: bash docker_push.sh
    skip_cleanup: true
    on:
      branch: master
      condition: -z "$TRAVIS_PULL_REQUEST_BRANCH"
#    tags: true / false  => has precendence over the branch condition
#    condition: "foo == bar && baz==bat"
#    repo: conduktor/kafka-security-manager
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file_glob: true
    file: "target/universal/kafka-security-manager-*.zip"
    skip_cleanup: true
    on:
      tags: true
      condition: -z "$TRAVIS_PULL_REQUEST_BRANCH"

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
