name: ScalaCI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  commit_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Run tests
      run: bash test.sh
      
    - name: create zip file
      run: sbt universal:packageBin
      if: startsWith(github.ref, 'refs/tags/v')
      
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: olafurpg/setup-scala@v10
    - run: sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    # - name: publish
    #   run: sbt publishSigned

    # - name: release snapshot
    #   run: sonatypeRelease
    
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: show release
      run: echo $RELEASE_VERSION

    - uses: docker-practice/actions-setup-docker@master
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: run docker script
      run: bash -x docker_push.sh
      
    - name: Release
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "true"
        ALLOW_TAG_PREFIX: "true"
      with:
        args: |
            target/universal/kafka-security-manager-*.zip
      if: startsWith(github.ref, 'refs/tags/v')
